### HaikuDepotServer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver
  labels:
    app: haikudepotserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikudepotserver
  strategy:
    # HDS needs a cross-instance cache before we can run multiple
    type: Recreate
  template:
    metadata:
      labels:
        app: haikudepotserver
    spec:
      containers:
      - name: haikudepotserver
        image: ghcr.io/haiku/haikudepotserver:1.0.177
        env:
        - name: HDS_BASE_URL
          value: "https://depot.haiku-os.org"
        - name: SPRING_MAIL_HOST
          value: "smtp"
        - name: HDS_JOBSERVICE_TYPE
          value: "db"
        - name: HDS_IS_PRODUCTION
          value: "true"
        - name: HDS_AUTHENTICATION_JWS_ISSUER
          value: "haikuinc.hds"
        - name: HDS_GRAPHICS_SERVER_BASE_URI
          value: "http://haikudepotserver-server-graphics:80"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/haikudepotserver"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-pg
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-pg
              key: password
        - name: HDS_ALERTS_REPOSITORY_ABSENT_UPDATES_TO
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-notify
              key: emails
        - name: HDS_AUTHENTICATION_JWS_SHARED_KEY
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-jws
              key: shared-key
        resources:
          limits:
            cpu: "1.0"
            memory: "1.0Gi"
          requests:
            cpu: "0.50"
            memory: "750Mi"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 60
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver-server-graphics
  labels:
    app: haikudepotserver-server-graphics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haikudepotserver-server-graphics
  template:
    metadata:
      labels:
        app: haikudepotserver-server-graphics
    spec:
      containers:
        - name: haikudepotserver-server-graphics
          image: ghcr.io/haiku/haikudepotserver-server-graphics:1.0.177
          env:
            - name: HDS_GFX_QUANTIZE
              value: "false"
          resources:
            limits:
              cpu: "1.0"
              memory: "320Mi"
            requests:
              cpu: "0.50"
              memory: "320Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver
spec:
  selector:
    app: haikudepotserver
  ports:
  - name: www
    port: 80
    targetPort: 8080
  - name: actuator
    # This exposes a maintenance / prob port from the main Application server. This port
    # should not be exposed externally.
    port: 81
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver-server-graphics
spec:
  selector:
    app: haikudepotserver-server-graphics
  ports:
    - name: www
      port: 80
      targetPort: 8085
---
# web frontends for haikudepotserver
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haikudepotserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - hosts:
    - depot.haiku-os.org
    secretName: tls-cert-haikudepotserver
  rules:
  - host: depot.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haikudepotserver
            port:
              name: www
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: haikudepotserver-pgbackup
spec:
  schedule: "0 0 * * 1,4"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: pgbackup
              image: ghcr.io/haiku/pgbackup:3.0.4
              args: ["backup", "haikudepotserver"]
              env:
              - name: REMOTE_PREFIX
                value: haiku-backups
              - name: REMOTE_MAX_AGE
                value: 15d
              - name: PG_HOSTNAME
                value: postgres
              - name: PG_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: username
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: password
              volumeMounts:
              - name: rclone-config
                mountPath: /root/.config
          volumes:
          - name: rclone-config
            secret:
              secretName: s3-backup
              items:
              - key: rclone.conf
                path: rclone/rclone.conf
              - key: twosecret
                path: twosecret
---
# This CronJob runs every hour hitting one of the HDS application server instances
# to run some maintenance logic.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: haikudepotserver-maintenance-hourly
spec:
  schedule: "14 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: haikudepotserver-maintenance-hourly
              image: curlimages/curl:8.13.0
              args:
                - curl
                - -X
                - POST
                - -H
                - Content-Type:application/json
                - --data
                - '{"type":"HOURLY"}'
                - http://haikudepotserver:81/actuator/hdsmaintenance
          restartPolicy: Never
---
# This CronJob runs every day hitting one of the HDS application server instances
# to run some logic.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: haikudepotserver-maintenance-daily
spec:
  schedule: "47 5 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: haikudepotserver-maintenance-daily
              image: curlimages/curl:8.13.0
              args:
                - curl
                - -X
                - POST
                - -H
                - Content-Type:application/json
                - --data
                - '{"type":"DAILY"}'
                - http://haikudepotserver:81/actuator/hdsmaintenance
          restartPolicy: Never
