# Serves haiku and haikuports repositories
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpkg-haiku
  labels:
    app: hpkg-haiku
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpkg-haiku
  template:
    metadata:
      labels:
        app: hpkg-haiku
    spec:
      containers:
      - name: hpkgbouncer
        image: ghcr.io/haiku/hpkgbouncer:0.4.5
        env:
        - name: ROCKET_LOG_LEVEL
          value: "normal"
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: ROCKET_PORT
          value: "8000"
        - name: CACHE_TTL
          value: "900"
        - name: S3_PUBLIC
          value: "https://haiku-repository.cdn.haiku-os.org/"
        volumeMounts:
        - name: secrets
          mountPath: "/var/run/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: s3-garage-haiku
          items:
          - key: s3_endpoint
            path: s3_endpoint
          - key: s3_bucket
            path: s3_bucket
          - key: s3_key
            path: s3_key
          - key: s3_secret
            path: s3_secret
          - key: s3_region
            path: s3_region
---
apiVersion: v1
kind: Service
metadata:
  name: hpkg-haiku
spec:
  selector:
    app: hpkg-haiku
  ports:
  - name: hpkg-haiku-www
    port: 80
    targetPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hpkg-haikuports-config
data:
  nginx.conf: |
    user nginx;
    worker_processes 3;
    error_log /dev/stdout;
    events {
      worker_connections 1024;
    }
    http {
      access_log /dev/stdout;
      server {
        listen 80;
        server_name _;
        location / {
          rewrite "^/master/build-packages/[a-f0-9]{64}/packages/(.*)$" https://haiku-buildpackages.cdn.haiku-os.org/packages/$1 redirect;
          rewrite "^/master/build-packages/([a-f0-9]{64}/.*)$" https://haiku-buildpackages.cdn.haiku-os.org/$1 redirect;
        }
        location /healthz {
          return 200 "healthy boi!\n";
        }
        #return 302 https://download.haiku-os.org;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpkg-haikuports-buildpackages
  labels:
    app: hpkg-haikuports-buildpackages
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpkg-haikuports-buildpackages
  template:
    metadata:
      labels:
        app: hpkg-haikuports-buildpackages
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:stable-alpine
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
          readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: hpkg-haikuports-config
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: hpkg-haikuports-buildpackages
spec:
  selector:
    app: hpkg-haikuports-buildpackages
  ports:
  - name: www
    port: 80
    targetPort: 80
---
# Serves haiku and haikuports repositories
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpkg-haikuports
  labels:
    app: hpkg-haikuports
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpkg-haikuports
  template:
    metadata:
      labels:
        app: hpkg-haikuports
    spec:
      containers:
      - name: hpkgbouncer
        image: ghcr.io/haiku/hpkgbouncer:0.4.5
        env:
        - name: ROCKET_LOG_LEVEL
          value: "normal"
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: ROCKET_PORT
          value: "8000"
        - name: CACHE_TTL
          value: "900"
        - name: S3_PUBLIC
          value: "https://haikuports-repository.cdn.haiku-os.org/"
        - name: BRANCH_ALIASES
          value: "master:r1beta5,r1beta4,r1beta3"
        volumeMounts:
        - name: secrets
          mountPath: "/var/run/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: s3-garage-haikuports
          items:
          - key: s3_endpoint
            path: s3_endpoint
          - key: s3_bucket
            path: s3_bucket
          - key: s3_key
            path: s3_key
          - key: s3_secret
            path: s3_secret
          - key: s3_region
            path: s3_region
---
apiVersion: v1
kind: Service
metadata:
  name: hpkg-haikuports
spec:
  selector:
    app: hpkg-haikuports
  ports:
  - name: hpkg-bouncer-www
    port: 80
    targetPort: 8000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-hpkg-prefix
spec:
  stripPrefix:
    prefixes:
      - /haikuports/
      - /haiku/
---
# web frontends for package repos
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hpkg
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-hpkg-prefix@kubernetescrd
spec:
  tls:
  - hosts:
    - eu.hpkg.haiku-os.org
    secretName: tls-cert-eu-hpkg
  rules:
  - host: eu.hpkg.haiku-os.org
    http:
      paths:
      - path: /haiku/
        pathType: Prefix
        backend:
          service:
            name: hpkg-haiku
            port:
              number: 80
      - path: /haikuports/master/build-packages/
        pathType: Prefix
        backend:
          service:
            name: hpkg-haikuports-buildpackages
            port:
              number: 80
      - path: /haikuports/
        pathType: Prefix
        backend:
          service:
            name: hpkg-haikuports
            port:
              number: 80
