### Haiku Userguide
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userguide
  labels:
    app: userguide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userguide
  strategy:
    # RollingUpgrade can't be used because of RWO storage
    type: Recreate
  template:
    metadata:
      labels:
        app: userguide
    spec:
      containers:
      - name: userguide
        image: ghcr.io/haiku/userguide:1.0-1
        env:
        - name: REF_DIR
          value: data/source_docs
        - name: EXPORT_DIR
          value: data/export/docs
        - name: IMPORT_DIR
          value: data/import
        - name: BASE_DOMAIN
          value: https://i18n.haiku-os.org
        - name: DB_SERVER
          value: postgres
        - name: DB_BASENAME
          valueFrom:
            secretKeyRef:
              name: userguide-pg
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: userguide-pg
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: userguide-pg
              key: password
        resources:
          limits:
            cpu: "0.50"
            memory: "1024Mi"
          requests:
            cpu: "0.25"
            memory: "64Mi"
        volumeMounts:
        - name: userguide-data
          mountPath: /var/app/userguide/data
      volumes:
      - name: userguide-data
        persistentVolumeClaim:
          claimName: userguide-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userguide-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: userguide
spec:
  selector:
    app: userguide
  ports:
  - name: web
    port: 80
    targetPort: 80
---
# web frontends for userguide
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userguide-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - hosts:
    - i18n.haiku-os.org
    secretName: tls-cert-i18n
  rules:
  - host: i18n.haiku-os.org
    http:
      paths:
      - path: /userguide
        pathType: Prefix
        backend:
          service:
            name: userguide
            port:
              name: web
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: userguide-pgbackup
spec:
  schedule: "0 0 * * 1,4"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: pgbackup
              image: ghcr.io/haiku/pgbackup:1.1
              args: ["backup", "userguide_production"]
              env:
              - name: S3_HOST
                value: "https://s3.eu-west-1.wasabisys.com"
              - name: S3_BUCKET
                value: haiku-backups
              - name: S3_MAX_AGE
                value: 15d
              - name: S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_key
              - name: S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_secret
              - name: TWOSECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: twosecret
              - name: PG_HOSTNAME
                value: postgres
              - name: PG_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: username
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: password
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: userguide-pvbackup
spec:
  schedule: "0 1 * * 1,4"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          # volumes are attached to a single physical node (RWO), this ensures the backup
          # job always starts on the same physical node where userguide is running
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - userguide
                topologyKey: kubernetes.io/hostname
          containers:
            - name: pvbackup
              image: ghcr.io/haiku/pvbackup:1.3
              args: ["backup", "userguide-data"]
              env:
              - name: S3_HOST
                value: "https://s3.eu-west-1.wasabisys.com"
              - name: S3_BUCKET
                value: haiku-backups
              - name: S3_MAX_AGE
                value: 15d
              - name: S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_key
              - name: S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_secret
              - name: TWOSECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: twosecret
              volumeMounts:
              - name: userguide-data
                mountPath: /pvs/userguide-data
          volumes:
          - name: userguide-data
            persistentVolumeClaim:
              claimName: userguide-data-pvc
          restartPolicy: Never
