#!/bin/sh

if [ -z "$MONITOR_PATHS" ]
then
	export MONITOR_PATHS="/etc/nginx/conf.d"
fi

for path in $MONITOR_PATHS; do
	echo "Auto-reload $path..."
	auto-reload $path &
done

echo "Starting nginx..."
exec nginx -g "daemon off;"
