#!/bin/sh

echo "log file = /dev/stdout" > /etc/rsyncd.conf
echo "port = 12000" >> /etc/rsyncd.conf
echo "use chroot = yes" >> /etc/rsyncd.conf
echo "max connections = 10" >> /etc/rsyncd.conf

for V in ${VOLUMES}; do
	SUBPATH=${V}
	if [ -f "${V}/.subpath" ]; then
		SUBPATH=$V/$(cat ${V}/.subpath)
	fi
	for D in ${SUBPATH}/*; do
		if [ -d "${D}" ]; then
			SHARENAME=$(basename "${D}")
			if [ -f "${D}/.sharename" ]; then
				SHARENAME=$(cat ${D}/.sharename)
			fi

			if grep -q "[$SHARENAME]" "/etc/rsyncd.conf"; then
				echo "Skipping duplicate share ref."
				continue
			fi
			echo "Injecting ${D} as ${SHARENAME}..."

			echo "[$SHARENAME]" >> /etc/rsyncd.conf
			echo "path = ${D}" >> /etc/rsyncd.conf
			echo "comment = ${SHARENAME}" >> /etc/rsyncd.conf
			echo "read only = true" >> /etc/rsyncd.conf
			echo "timeout = 300" >> /etc/rsyncd.conf

			echo "hosts deny = *" >> /etc/rsyncd.conf
			ALLOW=""
			if [ -f /repo-whitelist/${SHARENAME}/rsync-whitelist ]; then
				for i in $(sed -e '/^#/d' /repo-whitelist/${SHARENAME}/rsync-whitelist); do
					ALLOW="${ALLOW} $i"
				done
			fi
			echo "hosts allow = ${ALLOW}" >> /etc/rsyncd.conf
		fi
	done
done

exec /usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf "$@"
