#!/usr/bin/python3

from datetime import datetime
import glob
import json
import os
import re
import sys
import time
from subprocess import call, check_call, check_output

def log(level, message, **fields):
	record = {
		'timestamp': datetime.now().strftime('%Y-%m-%dT%H:%M:%S'),
		'level': level,
		'message': message,
	}
	record.update(fields)
	print(json.dumps(record), flush=True)

# constants
gitRepos = [
	['/ports-mirror/haikuports.git', 'https://github.com/haikuports/haikuports'],
	['/ports-mirror/haikuports.cross.git', 'https://github.com/haikuports/haikuports.cross'],
]

downloadDir = '/tmp/ports-mirror.in'

# Source packages are archived to an S3 bucket in a <recipeName>/<filename>
# layout, keyed by the recipe name and the source filename.
s3Bucket = os.environ.get('S3_BUCKET')
s3Endpoint = os.environ.get('S3_ENDPOINT')
s3Region = os.environ.get('S3_REGION')
s3AccessKey = os.environ.get('S3_ACCESS_KEY')
s3SecretKey = os.environ.get('S3_SECRET_KEY')

if not (s3Bucket and s3Endpoint and s3Region and s3AccessKey and s3SecretKey):
	log('error', 'S3_BUCKET, S3_ENDPOINT, S3_REGION, S3_ACCESS_KEY, and S3_SECRET_KEY are required!')
	sys.exit(1)

import boto3
from botocore.client import Config
from botocore.exceptions import ClientError

s3Client = boto3.client(
	's3',
	endpoint_url=s3Endpoint,
	region_name=s3Region,
	aws_access_key_id=s3AccessKey,
	aws_secret_access_key=s3SecretKey,
	config=Config(signature_version='s3v4'),
)

if not os.path.exists(downloadDir):
	os.mkdir(downloadDir)

shellVars = dict()
recipe = ''

class Replacer(object):
	def __init__(self, recipe):
		self.recipe = recipe

	def __call__(self, match):
		shellVar = match.group(1)
		if shellVar not in shellVars:
			shellVarSpecMatch = re.search('^' + shellVar + '="(.+?)"', self.recipe, flags=re.DOTALL | re.MULTILINE)
			if not shellVarSpecMatch:
				return match.group(0)
			shellVars[shellVar] = shellVarSpecMatch.group(1)
		return shellVars[shellVar]

def expandVariables(string, recipe):
	replacer = Replacer(recipe)
	string = re.sub(r'\$(\w+)', replacer, string)
	return re.sub(r'\$\{(\w+)\}', replacer, string)

def s3ObjectValid(s3target, expectedSha256):
	# Returns True when the object exists in the bucket and the sha256 checksum
	# recorded on it matches the one described in the recipe.  Objects that are
	# missing, that predate checksum recording, or whose checksum does not match
	# are considered invalid so they get re-downloaded and re-archived.
	try:
		head = s3Client.head_object(Bucket=s3Bucket, Key=s3target)
	except ClientError as e:
		if e.response['Error']['Code'] == '404':
			return False
		raise
	return head.get('Metadata', {}).get('sha256') == expectedSha256

def updateRecipe(recipeFile):
	with open(recipeFile, 'r') as f:
		recipe = f.read()

	if 'ARCHITECTURES="' not in recipe:
		return

	recipeFileName = os.path.basename(recipeFile)
	recipeName = recipeFileName.partition('-')[0]

	shellVars.clear()
	shellVars['portName'] = os.path.basename(recipeFile).partition('-')[0]
	shellVars['portVersion'] = os.path.basename(recipeFile).partition('-')[2][:-7]
	shellVars['portVersionedName'] = shellVars['portName'] + '-' + shellVars['portVersion']

	for srcUriMatch in re.finditer(r'^(SOURCE_URI(?:_\d+)*)="(.+?)"', recipe, flags=re.DOTALL | re.MULTILINE):
		srcUriKey = srcUriMatch.group(1)
		srcFilenameKey = srcUriKey.replace('SOURCE_URI', 'SOURCE_FILENAME')
		checksumSha256Key = srcUriKey.replace('SOURCE_URI', 'CHECKSUM_SHA256')
		for srcUriSpec in srcUriMatch.group(2).split():
			if not (srcUriSpec.startswith('http') or srcUriSpec.startswith('ftp')):
				return
			srcUri = srcUriSpec.partition('#')[0]
			srcUri = expandVariables(srcUri, recipe)
			srcFilenameMatch = re.search('^' + srcFilenameKey + '="(.+?)"', recipe,
				flags=re.DOTALL | re.MULTILINE)
			if srcFilenameMatch:
				filename = srcFilenameMatch.group(1)
			elif 'sourceforge.net' in srcUri and srcUri.endswith('download'):
				filename = os.path.basename(os.path.dirname(srcUri))
			else:
				filename = os.path.basename(srcUri)
			filename = expandVariables(filename, recipe)
			borkedMarkerPath = downloadDir + '/' + filename + '.is_borked'
			if os.path.exists(borkedMarkerPath):
				return
			s3target = recipeName + '/' + filename
			downloadpath = downloadDir + '/' + filename
			checksumMatch = re.search('^' + checksumSha256Key + '="(.+?)"', recipe,
				flags=re.DOTALL | re.MULTILINE)
			if checksumMatch and s3ObjectValid(s3target, checksumMatch.group(1)):
				return
			log('info', os.path.basename(recipeFile) + ' => ' + filename + " (" + srcUri + ")",
				recipe=recipeFileName, filename=filename, uri=srcUri)
			if not checksumMatch:
				log('error', 'recipe ' + recipeFile + ' does not contain a usable checksum!')
				return
			if os.path.exists(downloadpath):
				os.remove(downloadpath)
			args = [ 'curl', '-fkL', '--limit-rate', '5M', '--silent', '--output', downloadpath, srcUri ]
			#args = [ 'curl', '-fkL', '--limit-rate', '5M', '--output', downloadpath, srcUri ]
			curlResult = call(args, cwd=downloadDir)
			if curlResult != 0:
				log('error', 'unable to download ' + filename + ' - curl gave resultcode ' + str(curlResult),
					filename=filename, curl_resultcode=curlResult)
				return

			checksum = check_output(['sha256sum', '-b', downloadpath], universal_newlines=True).split()[0]
			if checksum != checksumMatch.group(1):
				log('error', 'SHA256-checksum mismatch for ' + filename,
					filename=filename, expected=checksumMatch.group(1), got=checksum)
				return

			try:
				s3Client.upload_file(downloadpath, s3Bucket, s3target,
					ExtraArgs={'Metadata': {'sha256': checksum}})
			except Exception as e:
				os.remove(downloadpath)
				log('error', 'unable to archive ' + filename + ' to s3://' + s3Bucket + '/' + s3target + ': ' + str(e),
					filename=filename, bucket=s3Bucket, key=s3target, error=str(e))
				return
			os.remove(downloadpath)


def updateFromCheckout(gitRepoDir):
	for recipeFile in glob.glob(gitRepoDir + '/*/*/*.recipe'):
		try:
			updateRecipe(recipeFile)
		except OSError as e:
			log('error', 'exception while processing ' + recipeFile + ': ' + str(e),
				recipe_file=recipeFile, error=str(e))
			continue

while True:
	for gitRepo in gitRepos:
		gitRepoDir = gitRepo[0]
		gitRepoUrl = gitRepo[1]
		repoName = gitRepoDir.split('/')[-1]

		if not os.path.exists(gitRepoDir):
			log('info', 'cloning %s from %s' % (repoName, gitRepoUrl),
				repo=repoName, url=gitRepoUrl)
			check_call([ 'git', 'clone', gitRepoUrl, gitRepoDir ])
		check_call([ 'git', 'fetch', '--all' ], cwd=gitRepoDir)

		branchesString = check_output([ 'git', 'branch', '-a' ], cwd=gitRepoDir, universal_newlines=True)
		branches = branchesString.splitlines()

		for branch in branches:
			branch = branch[2:]
			if branch.startswith("(HEAD"):
				continue
			if ' ' in branch:
				branch = branch[0:branch.find(' ')]
			log('info', 'updating %s/%s' % (repoName, branch),
				repo=repoName, branch=branch)
			check_call([ 'git', 'checkout', '-q', branch ], cwd=gitRepoDir)

			updateFromCheckout(gitRepoDir)

	time.sleep(60 * 60 * 6) # 6 hours
