#!/bin/bash

# TIP: Run this one as root if you're using s3 + fuse
#      for the source files

export PATH=$PATH:/usr/local/bin

echo "Syncing Haiku Repository master..."
mfs-sync-haiku master
echo "Syncing Haiku Repository r1beta2..."
mfs-sync-haiku r1beta2
echo "Syncing Haiku Repository r1beta3..."
mfs-sync-haiku r1beta3
