#!/bin/bash
#
# Grab latest haikuports, sync to IPFS and publish
#
# Expectations:
#  * ipfs cli in /usr/local/bin
#  * room in home directory for haikuports
#  * mfs-publish script

LOG="/tmp/haikuports-sync.log"
exec 1>$LOG
exec 2>&1

export PATH=$PATH:/usr/local/bin

# TODO: this is pretty inefficent. There are various ipfs mirroring / sync tools
# in development, but none are really viable when this was written.

rsync -aP --delete rsync://rsync.haiku-os.org:12000/haikuports-master haikuports/master
HASH=$(ipfs add -r -Q haikuports)

echo "Setting haikuports to $HASH..."
ipfs files rm -r /haikuports || true
ipfs files cp /ipfs/$HASH /haikuports

mfs-publish
