#!/bin/bash
#
# Grab latest haikuports, sync to IPFS and publish
#
# Expectations:
#  * ipfs cli in /usr/local/bin
#  * room in home directory for haikuports
#  * mfs-publish script

# IPFS Server
IPFS_API_SERVER="127.0.0.1"
IPFS_API_PORT="5001"

export PATH=$PATH:/usr/local/bin

# TODO: this is pretty inefficent. There are various ipfs mirroring / sync tools
# in development, but none are really viable when this was written.

curl -sSf http://$IPFS_API_SERVER:$IPFS_API_PORT/version
if [ $? -ne 0 ]; then
	echo "ERROR: IPFS Daemon not running!"
	exit 1
fi
export IPFS="ipfs --api /ip4/$IPFS_API_SERVER/tcp/$IPFS_API_PORT"

rsync -aP --delete rsync://rsync.haiku-os.org:12000/haikuports-master ~/haikuports/master
HASH=$($IPFS add -r -Q ~/haikuports)

echo "Setting haikuports to $HASH..."
$IPFS files rm -r /haikuports || true
$IPFS files cp /ipfs/$HASH /haikuports
