FROM docker.io/alpine:3.22
RUN apk update \
  && apk add --no-cache apache2-utils bash bind-tools \
     curl drill ethtool file fping iotop iftop iperf iperf3 \
     iproute2 ipset jq ltrace mtr netcat-openbsd ngrep nmap \
     nmap-nping nmap-scripts openssl \
     postgresql15-client postgresql16-client postgresql17-client \
     scapy socat speedtest-cli openssh rsync rclone strace tcpdump \
     tcptraceroute tshark util-linux vim git websocat
