#!/bin/sh

if [ ! -f /secrets/s3-nightlies.toml ]; then
	echo "Missing s3 secrets at /secrets/s3!"
	exit 1
fi

cd /generate-download-pages

while true; do
	echo "generate-download-pages.py running..."
	/usr/bin/python3 /generate-download-pages/generate-download-pages.py --config /secrets/s3-nightlies.toml
	sleep 1800
done
