#!/bin/bash

# Setup Symlinks
if [[ ! -L /var/lib/logrotate ]]; then
  rm -fr /var/lib/logrotate
  mkdir -p /shared/state/logrotate
  ln -s /shared/state/logrotate /var/lib/logrotate
fi
if [[ ! -L /var/spool/anacron ]]; then
  rm -fr /var/spool/anacron
  mkdir -p /shared/state/anacron-spool
  ln -s /shared/state/anacron-spool /var/spool/anacron
fi
if [[ ! -d /shared/log/rails ]]; then
  mkdir -p /shared/log/rails
  #chown -R discourse:www-data /shared/log/rails
fi
if [[ ! -d /shared/uploads ]]; then
  mkdir -p /shared/uploads
  #chown -R discourse:www-data /shared/uploads
fi
if [[ ! -d /shared/backups ]]; then
  mkdir -p /shared/backups
  #chown -R discourse:www-data /shared/backups
fi

rm -rf /shared/tmp/{backups,restores}
mkdir -p /shared/tmp/{backups,restores}
#chown -R discourse:www-data /shared/tmp/{backups,restores}

# Setup
mkdir -p /var/log/nginx
chown -R www-data:www-data /var/log/nginx
chmod -R 644 /var/log/nginx
chmod 755 /var/log/nginx
#touch /var/log/syslog   && chown -f syslog:adm /var/log/syslog*
#touch /var/log/auth.log && chown -f syslog:adm /var/log/auth.log*
#touch /var/log/kern.log && chown -f syslog:adm /var/log/kern.log*

# Overlay our secrets
if [[ -f /shared/secrets.env ]]; then
	echo "Processing /shared/secrets.env..."
	source /shared/secrets.env
else
	echo "Warning: No secrets found at /shared/secrets.env!"
fi

# Write out config
env > ~/boot_env
conf=/apps/discourse/config/discourse.conf
# find DISCOURSE_ env vars, strip the leader, lowercase the key
ruby -e 'ENV.each{|k,v| puts "#{$1.downcase} = '\''#{v}'\''" if k =~ /^DISCOURSE_(.*)/}' > $conf

# Pre-compile assets
cd /apps/discourse && bundle exec rake assets:precompile

# Apply migrations
cd /apps/discourse && bundle exec rake db:migrate

supervisord --nodaemon --configuration /etc/supervisord.conf
