#!/bin/bash

# This gets data from limerick and updates k8s with it.
# Ideally we'll run this continiously to keep infrastructure
# in sync.
#
# When we switch over the entry needs disabled.
#

# redis.yml
./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/support_redis_data/_data/. redis-data-pvc
# development.yml
./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/dev_gerrit_data/_data/. gerrit-data-pvc
# mail.yml
./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/support_smtp_keys/_data/. smtp-keys-pvc
# discourse.yml
./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/community_discourse_shared/_data/. discourse-data-pvc
# trac.yml
./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/dev_trac_data/_data/. trac-data-pvc

# buildmaster.yml
#./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/ci_data_master_x86_64/_data/. buildmaster-data-x86-64-pvc
#./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/ci_data_master_x86_gcc2/_data/. buildmaster-data-x86-64-pvc
#./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/volumes/ci_sources/_data/. buildmaster-sources-pvc
#
##./volume_migrator.sh root@limerick.ams3.haiku-os.org:/var/lib/docker/plugins/0b25ebdee8b48451b1459c6c1965570c948ef97028d78e96057a0962b482ce84/propagated-mount/volumes/ci-packages/data/. \
##	buildmaster-packages-pvc
