#!/bin/bash
#
# I create fake ssl certifcates. These are not valid, but help nginx
# to start when real certs are not present (like on development systems)
#
# You *really* shouldn't run me on production servers since i'll wipe out
# valid certificates.
#
# To regenerate fakecerts, rm -rf /etc/letsencrypt/live/*

CERT_ROOT="/etc/letsencrypt/live"
DOMAINS="git.haiku-os.org cgit.haiku-os.org review.haiku-os.org"
mkdir -p $CERT_ROOT
for i in $DOMAINS; do
	if [ -d $CERT_ROOT/$i ]; then
		echo "warning: skipping $i since it already exists"
		continue
	fi
	mkdir $CERT_ROOT/$i

	openssl genrsa 2048 > $CERT_ROOT/$i/privkey.pem

	# The local- prefix is to prevent HSTS from freaking out.
	openssl req -x509 -days 30 -new -key $CERT_ROOT/$i/privkey.pem -subj "/CN=$i/O=Haiku Testing Infrastructure/C=US" -out $CERT_ROOT/$i/fullchain.pem
done
